#[derive(Debug, Clone)]
pub enum Command {
    AlternateScreenBuffer(bool),
    Backspace,
    BrackPasteMode(bool),
    CarriageReturn,
    ClearAbove,
    ClearBelow,
    ClearCount(i16),
    ClearLine,
    ClearLineAfterCursor,
    ClearLineBeforeCursor,
    ClearScreen,
    Exit,
    MoveCursor(i16, i16),
    MoveCursorAbsoluteHorizontal(i16),
    MoveCursorHorizontal(i16),
    MoveCursorLineVertical(i16),
    MoveCursorVertical(i16),
    NewLine,
    Print(char),
    ReportCursorPosition,
    ResetStyles,
    SGR(Vec<i16>),
}
