pub enum IdentifyTerminalMode {
    Primary,
    Secondary,
}

pub enum Command {
    AlternateScreenBuffer(bool),
    Backspace,
    BrackPasteMode(bool),
    CarriageReturn,
    ClearAbove,
    ClearBelow,
    ClearCount(i16),
    ClearLine,
    ClearLineAfterCursor,
    ClearLineBeforeCursor,
    ClearScreen,
    Exit,
    IdentifyTerminal(IdentifyTerminalMode),
    LineFeed,
    MoveCursor(i16, i16),
    MoveCursorAbsoluteHorizontal(i16),
    MoveCursorHorizontal(i16),
    MoveCursorLineVertical(i16),
    MoveCursorVertical(i16),
    NewLine,
    Print(char),
    PutTab,
    ReportCondition(bool),
    ReportCursorPosition,
    ResetStyles,
    RestoreCursor,
    SGR(Vec<i16>),
    SaveCursor,
    ShowCursor,
    SwapScreenAndSetRestoreCursor,
}
