pub enum Command {
    AlternateScreenBuffer(bool),
    Backspace,
    BrackPasteMode(bool),
    CarriageReturn,
    ClearAbove,
    ClearBelow,
    ClearScreen,
    Exit,
    NewLine,
    Print(char),
    ResetStyles,
    MoveCursor(i16, i16),
    MoveCursorAbsoluteHorizontal(i16),
    MoveCursorHorizontal(i16),
    MoveCursorVertical(i16),
    MoveCursorLineVertical(i16),
    ClearLineAfterCursor,
    ClearLineBeforeCursor,
    ClearLine,
    ClearCount(i16),
}
